### PR TITLE
Remove old lfortran builds to reduce repo size

### PR DESCRIPTION
**Pull request by ubaidsk**

### CODE REVIEW

**Comment by ubaidsk** [comment]
It looks like we will have to reset the whole repository instead of just deleting the builds.

**Comment by ubaidsk** [comment]
Just to be safe, I have created a fork of this repository here https://github.com/Shaikh-Ubaid/wasm_builds.

**Comment by certik** [comment]
Go for it. Let me know if you need any permissions.

**Comment by ubaidsk** [comment]
>Go for it. Let me know if you need any permissions.

It is done. Just awaiting the CI here https://github.com/lfortran/lfortran/pull/4433 to conclude. If the CI becomes green, then everything is good.

**Pull request closed without merging**
